name: Deploy to Prouction

on: 
  push: 
    branch:
      - main
jobs:
  build-and-deploy:
    runs-on: ubunto-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-nod@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --force

      - name: Build Project
        run: npm run build
      
      - name: Creating deployment artifact
        env: 
          GITHUB_SHA : ${{ github.sha}}
        run: tar -czf "${GITHUB_SHA}".tar.gz build
      
      - name: Storign artifact
        uses: actions/upload-artifact@c3
        with:
          name: app-build
          path: ${{ github.sha}}.tar.gz